services:
  postgres:
    # image: quay.io/debezium/example-postgres:3.0
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "wal_sender_timeout=300s" # 5 min
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cdc-bridge

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    command: -js  -sd /data -m 8222
    volumes:
      - nats-data:/data
    restart: unless-stopped
    networks:
      - cdc-bridge

  nats-init:
    image: natsio/nats-box:latest
    container_name: nats-init
    networks:
      - cdc-bridge
    depends_on:
      - nats-server
    command:
      - sh
      - -c
      - |
        echo 'Waiting for NATS server...'
        until nats server check connection --server=nats://nats-server:4222 2>/dev/null; do
          echo 'NATS not ready yet, retrying in 1s...'
          sleep 1
        done
        echo 'NATS server is ready!'
        echo 'Creating NATS JetStream stream: CDC'
        nats stream add CDC --server=nats://nats-server:4222 --subjects='cdc.>' --storage=file --retention=limits --max-age=1m --max-msgs=1000000 --max-bytes=1G --replicas=1 --defaults
        echo 'Stream CDC created successfully'
    restart: "no"

volumes:
  postgres-data:
    driver: local
  nats-data:
    driver: local

networks:
  cdc-bridge:
